spring: 
  profiles: 
    active: -dev
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: config-client-dev
eureka: 
  client: 
    service-url: 
      defaultZone: http://server9001:9001/eureka/
---
server: 
  port: 8202
spring: 
  profiles: uat
  application: 
    name: config-client-uat
eureka: 
  client: 
    service-url: 
      defaultZone: http://server9001:9001/eureka/