spring: 
  profiles: 
    active: -dev
---
server: 
  port: 9001

spring: 
  profiles: dev
  application: 
    name: server-config-dev

eureka: 
  instance:
    hostname: server9001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://server9001:9001/eureka/
